### ISSUE TITLE
Switch Float to Rational

### ISSUE THREAD

**Issue by glottologist** [marigold-dev/batcher#228]
After some comments from @tomjack about the safety of the Float lib, we should try to swap it out for Rational.

**Comment by kienle371999** [comment]
- In my opinion, the float module of `math_lib` is simple, and it is also tested carefully. Moreover, we included its particular version in the batcher codebase so we can use it instead of using the rational type.  
- Everyone can see the float module [here](https://github.com/ligolang/math-lib-cameligo/blob/main/float/float.mligo).

**Comment by glottologist** [comment]
@tj825 Agreed, better just not to take the chance.
